directories:
  stored_csv_directory: data/csv
  sqldb_directory: data/sqldb.db
  uploaded_files_sqldb_directory: data/uploaded_files_sqldb.db
  stored_csv_sqldb_directory: data/csv_sqldb.db
  persist_directory: data/chroma

llm_config:
    agent_llm_system_role: "Given the following user question, corresponding SQL query, and SQL result, answer the user question.\n
    Question: {question}\n
    SQL Query: {query}\n
    SQL Result: {result}\n
    Answer: 
    "
    engine: "gpt-35-turbo"
    temperature: 0.0

